# Generated by Django 5.0.6 on 2024-06-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
    ]
