# Generated by Django 5.0.6 on 2024-06-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
        ('State', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', default='', on_delete=django.db.models.deletion.CASCADE, to='State.statemodel'),
        ),
    ]
