# Generated by Django 5.0.6 on 2024-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_title', models.CharField(max_length=30)),
                ('coupon_code', models.CharField(max_length=30)),
                ('coupon_date', models.CharField(max_length=20)),
                ('coupon_noofuse', models.IntegerField(max_length=30)),
                ('coupon_active', models.CharField(max_length=5)),
                ('artical_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_coupon',
            },
        ),
    ]
