# Generated by Django 5.0.6 on 2024-06-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='coupon_noofuse',
            field=models.IntegerField(),
        ),
    ]
