# Generated by Django 5.0.6 on 2024-06-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_alter_couponmodel_coupon_noofuse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='artical_description',
            new_name='coupon_description',
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='coupon_date',
            field=models.DateField(),
        ),
    ]
