# Generated by Django 5.0.6 on 2024-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
