# Generated by Django 5.0.6 on 2024-06-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_pid_productmodel_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_img1',
            field=models.CharField(default='abc.jpg', max_length=30),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_img2',
            field=models.CharField(default='abc.jpg', max_length=30),
        ),
    ]
