# Generated by Django 5.0.6 on 2024-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_xender', models.CharField(max_length=30)),
                ('product_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tbl_employee',
            },
        ),
    ]
