# Generated by Django 5.0.6 on 2024-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='product_description',
            new_name='employee_description',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='product_xender',
            new_name='employee_xender',
        ),
    ]
