# Generated by Django 5.0.6 on 2024-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_product_description_employeemodel_employee_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='employee_description',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employee_department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_xender',
            field=models.CharField(max_length=10),
        ),
    ]
