# Generated by Django 5.0.6 on 2024-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_rename_employee_xender_employeemodel_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='employee_photo_id',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
