# Generated by Django 5.0.6 on 2024-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_employeemodel_employee_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_photo_id',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
