# Generated by Django 5.0.6 on 2024-06-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_citymodel_state_id'),
        ('Employee', '0007_employeemodel_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', default='', on_delete=django.db.models.deletion.CASCADE, to='City.citymodel'),
        ),
    ]
