# Generated by Django 5.0.6 on 2024-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categorymodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_img',
            field=models.CharField(max_length=100),
        ),
    ]
