# Generated by Django 5.0.6 on 2024-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersModel',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=30)),
                ('offer_description', models.CharField(max_length=100)),
                ('offer_maxvalue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('offer_minvalue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('offer_discount', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
            options={
                'db_table': 'tbl_offers',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
    ]
