# Generated by Django 5.0.6 on 2024-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AricalModel',
            fields=[
                ('artical_id', models.AutoField(primary_key=True, serialize=False)),
                ('artical_title', models.CharField(max_length=30)),
                ('artical_description', models.CharField(max_length=50)),
                ('artical_active', models.CharField(max_length=5)),
                ('artical_authors', models.CharField(max_length=20)),
                ('artical_date', models.DateTimeField()),
                ('artical_quote', models.CharField(max_length=30)),
            ],
        ),
    ]
