# Generated by Django 5.0.6 on 2024-05-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aricalmodel',
            table='tbl_artical',
        ),
    ]
