# Generated by Django 5.0.6 on 2024-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articls', '0002_alter_aricalmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aricalmodel',
            name='artical_date',
            field=models.IntegerField(),
        ),
    ]
