# Generated by Django 5.0.6 on 2024-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articls', '0003_alter_aricalmodel_artical_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aricalmodel',
            name='artical_date',
            field=models.CharField(max_length=20),
        ),
    ]
