# Generated by Django 5.0.6 on 2024-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel_2',
            fields=[
                ('product_2_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_2_name', models.CharField(max_length=30)),
                ('product_2_img1', models.ImageField(upload_to='media')),
                ('product_2_img2', models.ImageField(upload_to='media')),
                ('product_2_price', models.IntegerField()),
                ('product_2_active', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
            ],
            options={
                'db_table': 'tbl_product_2',
            },
        ),
    ]
