# Generated by Django 5.0.6 on 2024-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel_2',
            name='product_2_img1',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='productmodel_2',
            name='product_2_img2',
            field=models.ImageField(upload_to='product'),
        ),
    ]
