# Generated by Django 5.0.6 on 2024-06-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_title', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_state', models.CharField(max_length=30)),
                ('address_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_address',
            },
        ),
    ]
