# Generated by Django 5.0.6 on 2024-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='address_line_2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
